
server:
  port: 8586
spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      routes:
        - id: RecommendationsService
          uri: lb://RecommendationsService
          predicates:
            - Path=/api/recommendations/**
        - id: PlaybackHistoryService
          uri: lb://PlaybackHistoryService
          predicates:
            - Path=/playback-history/**
        - id: MediaService
          uri: lb://media-service
          predicates:
            - Path=/api/media/**
        - id: DonatelloUserService
          uri: lb://DonatelloUserService
          predicates:
            - Path=/users/**
        - id: ArtistService
          uri: lb://ArtistService
          predicates:
            - Path=/artist/**
        - id: SearchFunctionService
          uri: lb://SearchFunctionService
          predicates:
            - Path=/api/search/**
        - id: TopMediaService
          uri: lb://top-media-service
          predicates:
            - Path=/topmedia/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.edufy: INFO
