server:
  port: 8080
spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      routes:
        - id: Wigellstravel
          uri: lb://Wigellstravel
          predicates:
            - Path=/api/v2/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eurekatravel.azurewebsites.net/eureka/

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    se.salts.Wigellstravel.services: INFO

